Ukraine_web_informer/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('forum/', include('forum.urls')),
    path('categories/', include('categories.urls')),
    path('news/', include('news.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

categories/urls.py
from django.urls import path
from .views import Categories

urlpatterns = [
    path('', Categories.as_view(), name='categories')
]

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('forum/', include('forum.urls')),
    path('categories/', include('categories.urls')),
    path('news/', include('news.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

categories/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField("Category's name", max_length=200, null=False)
    description = models.CharField("Category's description", max_length=600, null=True, blank=True)

    def __str__(self) -> str:
        return self.name
 
    class Meta:
        verbose_name_plural = "Categories"

forum/models.py
from django.db import models
from accounts.models import CustomUser
from categories.models import Category

class Topic(models.Model):
    title       = models.CharField("Title", max_length=70, null=False)
    description = models.CharField("Pre-text", max_length=300, null=True)
    text        = models.TextField("Full-text", null=False)
    category    = models.ForeignKey(Category, on_delete = models.CASCADE)

    def __str__(self) -> str:
        return self.title

class Message(models.Model):
    text        = models.TextField("Comment text", null=False)
    sended_from = models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    topic       = models.ForeignKey(Topic, on_delete = models.CASCADE)
    time        = models.DateTimeField("Date/time", auto_now_add=True)

    def __str__(self) -> str:
        return self.text

class Reply(models.Model):
    text        = models.TextField("Comment text", null=False)
    sended_from = models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    time        = models.DateTimeField("Date/time", auto_now_add=True)
    reply_to    = models.ForeignKey(Message, on_delete = models.CASCADE)

    def __str__(self) -> str:
        return self.text

    class Meta:
        verbose_name_plural = "Replies"

class Receiver(models.Model):
    reply       = models.OneToOneField(Reply, on_delete = models.CASCADE)
    user        = models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    is_read     = models.BooleanField(null=False, default=False)

categories/views.py
from django.views import View
from django.shortcuts import render
from .models import Category
from django.core.handlers.wsgi import WSGIRequest

class Categories(View):
    def get(self, request: WSGIRequest):
        context = {}
        context['categories'] = Category.objects.all()
        return render(request, 'categories.html', context=context)

categories/templates/categories.html
{% extends 'base.html' %}

{% load static %}

{% block main %}

<div class="container container__lg">

  <!-- .forum -->
  <div class="forum">

    <!-- .forumBreadcrumb -->
    <div class="forumBreadcrumb">
      Categories /
    </div><!-- /.forumBreadcrumb -->

    {% for category in categories %}

    <!-- .forumItem -->
    <div class="forumItem">
      <span class="forumItem__icon">
        <img src="{% static 'images/message.svg' %}" alt="#">
      </span>
      <div class="forumItem__desc">
        <div class="forumItem__desc__name"><a href="{% url 'topics' %}?category={{ category.id }}">{{ category.name }}</a></div>
        <div class="forumItem__desc__text">{{ category.description }}</div>
      </div>
      <div class="forumItem__counters">
        <div class="forumItem__counter">
          <span class="forumItem__counter__number">{{ category.topic_set.count }}</span>
          <span class="forumItem__counter__name">Topics</span>
        </div>
      </div>
    </div><!-- /.forumItem -->

    {% endfor %}

  </div><!-- /.forum -->
</div>

{% endblock %}