Ukraine_web_informer/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('forum/', include('forum.urls')),
    path('categories/', include('categories.urls')),
    path('news/', include('news.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('forum/', include('forum.urls')),
    path('categories/', include('categories.urls')),
    path('news/', include('news.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path
from .views import Topics, Topic_view

urlpatterns = [
    path('', Topics.as_view(), name='topics'),
    path('topic', Topic_view.as_view(), name='topic'),
]

forum/models.py
from django.db import models
from accounts.models import CustomUser
from categories.models import Category

class Topic(models.Model):
    title       = models.CharField("Title", max_length=70, null=False)
    description = models.CharField("Pre-text", max_length=300, null=True)
    text        = models.TextField("Full-text", null=False)
    category    = models.ForeignKey(Category, on_delete = models.CASCADE)

    def __str__(self) -> str:
        return self.title

class Message(models.Model):
    text        = models.TextField("Comment text", null=False)
    sended_from = models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    topic       = models.ForeignKey(Topic, on_delete = models.CASCADE)
    time        = models.DateTimeField("Date/time", auto_now_add=True)

    def __str__(self) -> str:
        return self.text

class Reply(models.Model):
    text        = models.TextField("Comment text", null=False)
    sended_from = models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    time        = models.DateTimeField("Date/time", auto_now_add=True)
    reply_to    = models.ForeignKey(Message, on_delete = models.CASCADE)

    def __str__(self) -> str:
        return self.text

    class Meta:
        verbose_name_plural = "Replies"

class Receiver(models.Model):
    reply       = models.OneToOneField(Reply, on_delete = models.CASCADE)
    user        = models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    is_read     = models.BooleanField(null=False, default=False)

forum/views.py
from django.views import View
from django.shortcuts import render
from .models import Topic, Category, Message, CustomUser, Reply, Receiver
from django.core.handlers.wsgi import WSGIRequest
from .database import Database

class Topics(View):
    def get(self, request: WSGIRequest):
        context = {}
        context['category'] = Category.objects.filter(id=request.GET.get('category')).first()
        context['topics'] = Topic.objects.filter(category_id=context['category'])
        return render(request, 'topics.html', context=context)

class Topic_view(View):
    db = Database()

    def get(self, request: WSGIRequest):
        context = {}
        context['topic'] = Topic.objects.filter(id=request.GET.get('topic')).first()
        context['messages'] =  Message.objects.filter(topic_id=context['topic'])

        if request.user.is_authenticated:
            self.db.read_message(request.user.id, request.GET.get('topic'))

        return render(request, 'topic.html', context=context)

    def post(self, request: WSGIRequest):
        context = {}

        if request.user.is_authenticated:

            if not request.POST.get('reply_to'):
                new_message = Message(
                    text        = request.POST.get('text'),
                    sended_from = CustomUser.objects.get(id = request.user.id),
                    topic       = Topic.objects.get(id=request.POST.get('topic')),
                )
                new_message.save()
            else:
                new_reply = Reply(
                    text        = request.POST.get('text'),
                    sended_from = CustomUser.objects.get(id = request.user.id),
                    reply_to    = Message.objects.get(id=request.POST.get('reply_to')),
                )
                new_reply.save()
                new_sended_to = Receiver(
                    reply   = new_reply,
                    user    = CustomUser.objects.get(id=request.POST.get('sended_to'))
                )
                new_sended_to.save()
            
            self.db.read_message(request.user.id, request.POST.get('topic'))

        context['topic'] = Topic.objects.filter(id=request.POST.get('topic')).first()
        context['messages'] =  Message.objects.filter(topic_id=context['topic'])
        return render(request, 'topic.html', context=context)

forum/templates/topic.html
{% extends 'base.html' %}

{% load static %}

{% block main %}

<div class="container container__lg">

  <!-- .forum -->
  <div class="forum">

    <!-- .backLink -->
    <a href="forum.html" class="backLink">
      <img src="{% static 'images/back.svg' %}" alt="Back">
    </a><!-- /.backLink -->

    <!-- .forumBreadcrumb -->
    <div class="forumBreadcrumb">
      <a href="{% url 'categories' %}">Categories</a> / <a href="{% url 'topics' %}?category={{ topic.category.id }}">{{ topic.category.name }}</a> / {{ topic.title }}
    </div><!-- /.forumBreadcrumb -->

    <!-- .newsPost__inner -->
    <div class="newsPost__inner">
      <h1 class="newsPost__title h2">{{ topic.title }}</h1>
      <p>
        {{ topic.text }}
      </p>
    </div><!-- /.newsPost__inner -->

    {% for message in messages %}

    <!-- .forumPost -->
    <div class="forumPost" id="message_{{ message.id }}">
      <div class="forumPost__panel">
        <div class="forumPost__panel__inner">

          {% if message.sended_from.image %}
          <span class="forumPost__ava"><img src="{{ message.sended_from.image.url }}" alt="#"></span>
          {% else %}
          <span class="forumPost__ava"><img src="{% static 'images/defaultUser.png' %}" alt="#"></span>
          {% endif %}

          <a href="mailto:{{ message.sended_from.email }}">{{ message.sended_from.first_name }}</a>
        </div>
        <div class="forumPost__panel__inner">
          <span>{{ message.time }}</span>
          <a onclick="copyUrl('{{ request.build_absolute_uri }}#message_{{ message.id }}', '{{ message.id }}', 'message')" role="button"><img src="{% static 'images/forum-share.svg' %}" alt="Share"></a>
          <a onclick="replyMessage('message_{{ message.id }}')" role="button"><img src="{% static 'images/forum-reply.svg' %}" alt="Reply"></a>
          <a href="">#{{ message.id }}</a>
        </div>
      </div>
      <div class="forumPost__content">
        <p>{{ message.text }}</p>
      </div>
      
      <span class="forumPost__reply--message" style="display: none;">
        <p><b>Reply to message:</b></p>
        <!-- .forumPost -->
        {% if not user.is_authenticated %}
          <div class="forumPost__guest">
            <p>You need logged in to reply to message</p>
            <a href="{% url 'login' %}" class="button">Login</a>
          </div>
        {% else %}
          <form action="{% url 'topic' %}?topic={{ topic.id }}" method="post">
            {% csrf_token %}
            <textarea class="textarea" name="text" rows="3" required></textarea>
            <button type="submit" class="button">Send a message</button>
            <input type="hidden" name="topic" value="{{ topic.id }}">
            <input type="hidden" name="type" value="reply">
            <input type="hidden" name="reply_to" value="{{ message.id }}">
            <input type="hidden" name="sended_to" value="{{ message.sended_from.id }}">
          </form>
        {% endif %}
      </span>

    </div><!-- /.forumPost -->

      {% for reply in message.reply_set.all %}
      <!-- .forumPost__tree -->
      <div class="forumPost forumPost__tree" id="reply_{{ reply.id }}">
        <div class="forumPost__panel">
          <div class="forumPost__panel__inner">
            
            {% if reply.sended_from.image %}
            <span class="forumPost__ava"><img src="{{ reply.sended_from.image.url }}" alt="#"></span>
            {% else %}
            <span class="forumPost__ava"><img src="{% static 'images/defaultUser.png' %}" alt="#"></span>
            {% endif %}

            <a href="mailto:{{ reply.sended_from.email }}">{{ reply.sended_from.first_name }}</a>
          </div>
          <div class="forumPost__panel__inner">
            <span>{{ reply.time }}</span>
            <a onclick="copyUrl('{{ request.build_absolute_uri }}#reply_{{ reply.id }}', '{{ reply.id }}', 'reply')" role="button"><img src="{% static 'images/forum-share.svg' %}" alt="Share"></a>
            <a onclick="replyMessage('reply_{{ reply.id }}')" role="button"><img src="{% static 'images/forum-reply.svg' %}" alt="Reply"></a>
            <a href="#">#{{ reply.id }}</a>
          </div>
        </div>
        <div class="forumPost__content">
          <p><a href="mailto:{{ reply.receiver.user.email }}">{{ reply.receiver.user.first_name }}</a>, {{ reply.text }}</p>
        </div>
        
        <span class="forumPost__reply--message" style="display: none;">
          <p><b>Reply to message:</b></p>
          <!-- .forumPost -->
          {% if not user.is_authenticated %}
            <div class="forumPost__guest">
              <p>You need logged in to reply to message</p>
              <a href="{% url 'login' %}" class="button">Login</a>
            </div>
          {% else %}
            <form action="{% url 'topic' %}?topic={{ topic.id }}" method="post">
              {% csrf_token %}
              <textarea class="textarea" name="text" rows="3" required></textarea>
              <button type="submit" class="button">Send a message</button>
              <input type="hidden" name="topic" value="{{ topic.id }}">
              <input type="hidden" name="type" value="reply">
              <input type="hidden" name="reply_to" value="{{ message.id }}">
              <input type="hidden" name="sended_to" value="{{ reply.sended_from.id }}">
            </form>
          {% endif %}
        </span>

      </div><!-- /.forumPost -->
      {% endfor %}

    {% endfor %}

    <div class="forumPost">
      <p><b>Message:</b></p>
    <!-- .forumPost -->
    {% if not user.is_authenticated %}
      <div class="forumPost__guest">
        <p>You need logged in to write a message</p>
        <a href="{% url 'login' %}" class="button">Login</a>
      </div>
    {% else %}
      <form action="{% url 'topic' %}?topic={{ topic.id }}" method="post">
        {% csrf_token %}
        <textarea class="textarea" name="text" rows="3" required></textarea>
        <button type="submit" class="button">Send a message</button>
        <input type="hidden" name="topic" value="{{ topic.id }}">
        <input type="hidden" name="type" value="message">
      </form>
    {% endif %}
    </div><!-- /.forumPost -->

  </div><!-- /.forum -->

</div>

{% endblock %}

forum/templates/topics.html
{% extends 'base.html' %}

{% load static %}

{% block main %}

<div class="container container__lg">

  <!-- .forum -->
  <div class="forum">

    <!-- .forumBreadcrumb -->
    <div class="forumBreadcrumb">
      <a href="{% url 'categories' %}">Categories</a> / {{ category.name }}
    </div><!-- /.forumBreadcrumb -->

    {% for topic in topics %}

    <!-- .forumItem -->
    <div class="forumItem">
      <span class="forumItem__icon">
        <img src="{% static 'images/message.svg' %}" alt="#">
      </span>
      <div class="forumItem__desc">
        <div class="forumItem__desc__name"><a href="{% url 'topic' %}?topic={{ topic.id }}">{{ topic.title }}</a></div>
        <div class="forumItem__desc__text">{{ topic.description }}</div>
      </div>
      <div class="forumItem__counters">
        <div class="forumItem__counter">
          <span class="forumItem__counter__number">{{ topic.message_set.count }}</span>
          <span class="forumItem__counter__name">Messages</span>
        </div>
      </div>
    </div><!-- /.forumItem -->

    {% endfor %}

  </div><!-- /.forum -->
</div>

{% endblock %}